POST http://localhost/api/article
Content-Type: application/json
Accept: application/json
Authorization: Bearer c2af0f70316a1f75064c0ce89489bd4fc82560ec

{
   "theme": "tech",
   "title": "Тестовая статья",
   "keywords": {
       "keyword0": "EXAMPLE",
       "keyword1": "EXAMPLE",
       "keyword2": "EXAMPLE",
       "keyword3": "EXAMPLE",
       "keyword4": "EXAMPLE",
       "keyword5": "EXAAAAAMPLE",
       "keyword6": "EXAMPLES"
   },
   "sizeFrom": 1,
   "word1": null,
   "images": ["https://via.placeholder.com/250x250"]
}